### ISSUE TITLE
How to instantiate the value of a material_input()?

### ISSUE THREAD

**Issue by danpbowen** [ericrayanderson/shinymaterial#1]
I'm trying to do this, but I don't think I see any functionality to do this in [the code](https://github.com/ericrayanderson/shinymaterial/blob/master/R/shiny-material-switch.R)...
`
material_input(
  type = "switch",
  input_id = "show_nutrients_selector",
  label = "Nutrients selector",
  off_label = "Off",
  on_label = "On",
  **value = "On"**
)
`

shiny's checkboxInput passes a _vlaue_ argument that allows you to instantiate it's value as TRUE or FALSE. I haven't quite wrapped my head around the material_input/switch code yet, to see how this would be implemented.

Or, is this already possible, and I'm just missing the solution?

**Comment by ericrayanderson** [comment]
You are correct; there is no functionality to set the initial value of a switch. I will add this to the list of future enhancements.

**Comment by ericrayanderson** [comment]
I am working on a development version with this feature in it.
switch and checkbox have the parameter "initial_value" (boolean).

The new version is uploaded to github, you can install it (assuming you have the package 'devtools' installed) via:

`devtools::install_git(url = "https://github.com/ericrayanderson/shinymaterial",
 branch = "dev_0.2.0")`
