### ISSUE TITLE
Add compatibility with renderUI

### ISSUE THREAD

**Issue by arpyem** [ericrayanderson/shinymaterial#11]
It would be awesome if you could render these outputs from the server, but it looks like this isn't possible at the moment. In addition, material_cards do not adapt their sizing to uiOutputs generated from the server. 

![capture](https://cloud.githubusercontent.com/assets/19480448/26742765/fee3ec44-47ac-11e7-9d17-a4e0f8461e71.PNG)

**Comment by ericrayanderson** [comment]
This would be a great feature, and the next logical thing to add to this package. Also, I will look into the issue with the cards.

**Comment by nfultz** [comment]
I also noticed that material_buttons and material_modals don't trigger events when generated from renderUI , but actionButtons still work?

**Comment by ericrayanderson** [comment]
Ya, there is definitely issues with the `renderUI`. This will be the next thing addressed.

**Comment by happyshows** [comment]
I'd like to bump up the priority of this issue.

renderUI is key to build in dependency rendering. Without it, the usability of this package will be very limited....

My issue below (not rendering at all)
![image](https://user-images.githubusercontent.com/3208181/33956262-a47ac9f4-e003-11e7-9af8-1e33ca19007d.png)
![image](https://user-images.githubusercontent.com/3208181/33956344-e04463be-e003-11e7-954e-91cdd92310df.png)

**Comment by happyshows** [comment]
minimal example
```
library(shiny)
library(shinymaterial)
library(visNetwork)
# Wrap shinymaterial apps in material_page
ui <- material_page(
  title = "Basic Page",
  tags$h1("Page Content"),
  uiOutput('ui_test')
)

server <- function(input, output) {
  output$ui_test <- renderUI({
    visNetworkOutput('vis_vn',width = "100%",height = 800)
  })
  
  output$vis_vn <- renderVisNetwork({
    isolate({
      nodes <- data.frame(id = 1:3)
      edges <- data.frame(from = c(1,2), to = c(1,3))
      visNetwork(nodes, edges)
    })
  })
}
shinyApp(ui = ui, server = server)
```

**Comment by ericrayanderson** [comment]
Please try the most recent dev version `devtools::install_github("ericrayanderson/shinymaterial")` with renderUI (using `material_inputs`).

Still working on a fix regarding the issue directly above this comment.

**Comment by ericrayanderson** [comment]
@arpyem The issue regarding the `material_card`: Are you still experiencing this with the most recent dev release? `devtools::install_github("ericrayanderson/shinymaterial")`.

Also, does putting the `material_card` call inside the `renderUI` (as opposed to in `ui.R`) solve this issue?

**Comment by ericrayanderson** [comment]
@nfultz `material_buttons` rendered from `renderUI` should now work in the most recent dev version.

`devtools::install_github("ericrayanderson/shinymaterial")`

**Comment by charlie86** [comment]
I'm seeing the same issue as @happyshows. With the latest dev version, no output with renderUI
