### ISSUE TITLE
Shinymaterial update no longer works

### ISSUE THREAD

**Issue by hamzadiaz** [ericrayanderson/shinymaterial#111]
After updating to latest shinymaterial(1.0.1) all my apps stopped working, none of the inputs get triggered.
The problem is in the console of RStudio there is no logging but in google chrome' console  i get:
Uncaught SyntaxError: Function statements require a function name
(index):1190 Uncaught TypeError: Cannot read property 'replace' of undefined
    at exports.InputBinding.getValue ((index):1190)
    at d (init_shiny.js:150)
    at f (init_shiny.js:220)
    at initShiny (init_shiny.js:283)
init_shiny.js:314 Uncaught TypeError: Cannot read property 'normalCall' of undefined
    at k (init_shiny.js:314)
init_shiny.js:381 Uncaught TypeError: Cannot read property 'normalCall' of undefined
    at n (init_shiny.js:381)

What has changed from the previous version? 

Thanks

**Comment by ericrayanderson** [comment]
Were you coming off version 1.0.0 prior to this?

**Comment by hamzadiaz** [comment]
Hey Eric, I was coming from 0.5.5, had to downgrade back to this version and it works again!:
`devtools::install_version("shinymaterial", version = "0.5.5", repos = "http://cran.us.r-project.org")`

Please when will this be fixed?

**Comment by ericrayanderson** [comment]
Can you send me a reproducible example? The new version is working on my end for my testing apps.

**Comment by hamzadiaz** [comment]
I fixed it, the thing is, My application has a lot of Javascript libraries, so maybe there was something that overwrote shiny js i checked library by library and found it.
