### ISSUE TITLE
Dropdown Update JS Syntax error

### ISSUE THREAD

**Issue by Seyphaton** [ericrayanderson/shinymaterial#115]
https://github.com/ericrayanderson/shinymaterial/blob/6796ea08fde90ea0f6bdedc4573163f1b04befb8/R/update-shiny-material-dropdown.R#L62

The R code above leads to JS syntax errors:
`.append('<li><span>&nbsp;some text</span></li>.append('<li><span>&nbsp;more text</span></li>.append`

Correct: add **')**
` ".append('<li><span>&nbsp;", names(choices)[i], "</span></li>')"`

Best regards

**Comment by ericrayanderson** [comment]
Thanks.

Fixed in dev version `remotes::install_github("ericrayanderson/shinymaterial")`
