### ISSUE TITLE
shinyBS Collapse panels not working

### ISSUE THREAD

**Issue by lisovyk** [ericrayanderson/shinymaterial#12]
```
library(shinymaterial)
library(shinyBS)
ui <- material_page(
    bsCollapse(
        id = "CollPanel",
        open = "Prepoc panel",
        bsCollapsePanel(
            "Preproc panel",
            "output1"
        ),
        bsCollapsePanel(
            "Graphs panel",
            "output2"
        )
    )
)
server <- function(input, output) {}
shinyApp(ui = ui, server = server)
```

Change to fluidPage to see the right output

**Comment by ericrayanderson** [comment]
shinyBS extends the usage of the bootstrap CSS library for shiny apps (similar to what shinymaterial does with materialize). A standard shiny app will include the bootstrap library (fluidPage, navbarPage, etc.), however a material_page will not load the bootstrap library. shinyBS relies on bootstrap being loaded.

One thing that may help is to call the bootstrap library within a material page. Shiny includes a helper function to do this: bootstrapLib().
```
ui <- material_page(
  bootstrapLib(),
  bsCollapse(...
```
This may help, but you may run into some issues with materialize and bootstrap having conflicting classes.

**Comment by lisovyk** [comment]
That'll suffice. Any chance you'll look into full integration of it? Seems like a good lib to use with shinymaterial.

**Comment by ericrayanderson** [comment]
Full integration would be difficult, because there are a lot of conflicting CSS classes between Bootstrap and Materialize. On any given web app, developers would typically only use one of these.
