### ISSUE TITLE
[feature request] Ability to add menu to material_side_nav()

### ISSUE THREAD

**Issue by nz-stefan** [ericrayanderson/shinymaterial#14]
It would be great if the side navigation drawer supported a menu similar to [shinydashboard::sidebarMenu() ](https://rdrr.io/cran/shinydashboard/man/sidebarMenu.html) and [shinydashboard::tabItems](https://rdrr.io/cran/shinydashboard/man/tabItems.html).

**Comment by jpzhangvincent** [comment]
Yes, hope to have this feature soon!

**Comment by ericrayanderson** [comment]
Yes, this is in the works.

**Comment by ericrayanderson** [comment]
Check out v0.4.0 on CRAN.

https://ericrayanderson.github.io/shinymaterial/#basic_side_nav_with_tabs

**Comment by ericrayanderson** [comment]
Check v0.4.1 on CRAN.
