### ISSUE TITLE
[feature request] Valuebox or tiles 

### ISSUE THREAD

**Issue by jpzhangvincent** [ericrayanderson/shinymaterial#15]
It would be nice to have the value/info box.  I tried to directly use the valuebox from shinydashboard but the color is not showed correctly. Thanks.

**Comment by msolano00** [comment]
@jpzhangvincent you should not use shinymaterial with shinydashboard, pick the one that suits your project better.

**Comment by ericrayanderson** [comment]
As said above, shinymaterial should not be mixed with shinydashboard.

**Comment by sandroraabe** [comment]
You can use `material_cards` with the `value` as `title` and the rest as body. Place that into a `material_column` (which should in turn be in a `material_row`) and you've done :)

**Comment by shosaco** [comment]
You can use `material_cards` with the `value` as `title` and the rest as body. Place that into a `material_column` of some small size (which should in turn be in a `material_row`) and you're done :)
