### ISSUE TITLE
Adding more content to the NavBar

### ISSUE THREAD

**Issue by msolano00** [ericrayanderson/shinymaterial#17]
Hi @ericrayanderson, first let me thank you for creating such an awesome package!

I don't have an issue, its more of a question. Can we add more stuff to the navbar, for example, an unordered list or maybe an icon additionally from the title?

I would be happy to work on a PR for this feature :smile: 

Regards
Marvin

**Comment by ericrayanderson** [comment]
That sounds like a good feature. Were you thinking an icon such as a link to a GitHub site, for example? Would you expect the programmer to include their own icon?

**Comment by msolano00** [comment]
@ericrayanderson yup, that is a good example. A lot of people are including nowadays multiple stuff in the header, so I think this might be useful.

**Comment by msolano00** [comment]
@ericrayanderson I could work on this over the weekend, let me know if you are ok with me making a contribution to your repo.

**Comment by ericrayanderson** [comment]
Yes, I am okay with that.

**Comment by ericrayanderson** [comment]
Closing this for now. Its an optional feature to possibly add at some point.
