### ISSUE TITLE
Any idea why the css wasn't applied?

### ISSUE THREAD

**Issue by happyshows** [ericrayanderson/shinymaterial#2]
![image](https://cloud.githubusercontent.com/assets/3208181/25139070/d42fd7fa-2421-11e7-9320-5e9e8186f437.png)

```
shinymaterial::material_input(
                    type = "switch",
                    input_id = "ms",
                    label = "Test",
                    initial_value = T,
                    off_label = "Hide",
                    on_label = "Show"
                  )
```

```
> sessionInfo()
R version 3.3.1 (2016-06-21)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.12.3 (Sierra)

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets 
[6] methods   base     

other attached packages:
[1] shiny_1.0.1.9000

loaded via a namespace (and not attached):
 [1] R6_2.2.0            htmltools_0.3.5    
 [3] tools_3.3.1         Rcpp_0.12.10.1     
 [5] jsonlite_1.4        digest_0.6.12      
 [7] xtable_1.8-2        httpuv_1.3.3       
 [9] mime_0.5            shinymaterial_0.1.0
```

**Comment by ericrayanderson** [comment]
Is the CSS working for any input?

E.g. button

**Comment by happyshows** [comment]
Don't think so. Showing some style but guess it's not the right one

![image](https://cloud.githubusercontent.com/assets/3208181/25143735/2931027e-2431-11e7-858a-e938f014fdc7.png)

**Comment by ericrayanderson** [comment]
Do you know if the CSS worked with the version of shinymaterial on CRAN?

**Comment by happyshows** [comment]
Just tried, not working either. Can this be related to css file not properly included in the package?

**Comment by ericrayanderson** [comment]
It could. I can't tell for sure without looking at your web inspector, but it might be due to the fact that Materialize is being loaded via a CDN. I will upload a version of shinymaterial to github that loads Materialize directly.

**Comment by ericrayanderson** [comment]
I updated the version on github to load Materialize. If you are still having issues let me know.

**Comment by happyshows** [comment]
![image](https://cloud.githubusercontent.com/assets/3208181/25158389/b81ef2ac-246d-11e7-95db-e52757fe5cf2.png)

minimal example code
```

library(shiny)
library(shinymaterial)


server <- function(input, output) {

}

ui <- fluidPage(
  shinymaterial::material_input(
    type = "switch",
    input_id = "ms",
    label = "Test",
    off_label = "Hide",
    on_label = "Show",
    initial_value = T
  )
)

shinyApp(ui = ui, server = server)
```

**Comment by ericrayanderson** [comment]
The issue is that you are using the function `fluidPage`, which loads the Bootstrap CSS library. To use `shinymaterial` (with the Materialize CSS library), you have to use `material_page`.

```r
library(shiny)
library(shinymaterial)

server <- function(input, output) {
}

ui <- material_page(
  title = "",
  shinymaterial::material_input(
    type = "switch",
    input_id = "ms",
    label = "Test",
    off_label = "Hide",
    on_label = "Show",
    initial_value = T
  )
)

shinyApp(ui = ui, server = server)
```

**Comment by happyshows** [comment]
cool thanks...
