### ISSUE TITLE
Add material design spinner

### ISSUE THREAD

**Issue by erikdf** [ericrayanderson/shinymaterial#26]
First of all, thanks for making available the shinymaterial package.

It would be interesting to add the material design spinner. Something like [this](https://material.angular.io/components/progress-spinner/overview) would be a nice way to handle requests that are slow.

**Comment by ericrayanderson** [comment]
Check out the dev version `devtools::install_github("ericrayanderson/shinymaterial")`.

`material_spinner_show()` & `material_spinner_hide()`

**Comment by erikdf** [comment]
That's awesome! This is exactly what I had in mind.
Thank you!
