### ISSUE TITLE
dropdown not working

### ISSUE THREAD

**Issue by JohnCoene** [ericrayanderson/shinymaterial#28]
Hi dropdown doesn't seem to work for me. Shouldn't it be:

```
shiny::HTML(
            paste0(
              "<select", ifelse(multiple == TRUE, " multiple", ""),
              " id='", input_id, "'",
              " class='shiny-material-dropdown'",
              ">"
            )
          )
```

missing quotes `'`  around id.

**Comment by ericrayanderson** [comment]
Fixed in dev version.

`devtools::install_github("ericrayanderson/shinymaterial")`

Please let me know if this doesn't solve your issue.
