### ISSUE TITLE
Implement `update_material_dropdown(choices=...)`

### ISSUE THREAD

**Issue by mbacou** [ericrayanderson/shinymaterial#29]
Just wondering if there is any reason why `update_material_dropdown()` can not update the `choices` argument (only `value` seems implemented so far).
Thanks!

**Comment by ericrayanderson** [comment]
Added this to the dev version. Can you see if the newest (dev) version fulfills this issue?
`devtools::install_github("ericrayanderson/shinymaterial")`

**Comment by mbacou** [comment]
Hi Eric,
Thanks, I tried a few hours back. I have a `material_dropdown()` that filters another `material_dropdown()`. `update_material_dropdown(choices=myfilteredchoices)` does not error out (as it did previously), but it does not seem to re-render the choice list either.

**Comment by ericrayanderson** [comment]
Okay, thanks for the info. Did you also specify the parameter `value`?

**Comment by ericrayanderson** [comment]
Here is a small RE I used for testing:
```

  library(shiny)
  library(shinymaterial)
  
  # Wrap shinymaterial apps in material_page
  ui <- material_page(
    title = "Update Dropdown",
    tags$h1("Page Content"),
    material_button(input_id = "go", label = "GO"),
    material_dropdown(input_id = "test", label = "test",
                      choices = c("Choice 1" = "choice_1",
                                  "Choice 2" = "choice_2")),
    plotOutput("myPlot")
  )
  
  server <- function(input, output, session) {
    
    output$myPlot <- renderPlot({
      plot(1:10, main = input$test)
    })
    
    observeEvent(input$go, {
      if(input$go == 0){
        return(NULL)
      }
      update_material_dropdown(
        session,
        "test",
        value = "choice 3",
        choices = c("Choice 3" = "choice 3",
                    "Choice 4" = "choice 4")
      )
    })
    
    
  }
  shinyApp(ui = ui, server = server)
```

**Comment by mbacou** [comment]
Tried setting `value=something`, it works but seems to have weird rendering issues (cannot see labels in the dropdown).

![image](https://user-images.githubusercontent.com/260325/34085729-be69ba98-e362-11e7-9dc3-599067d2700d.png)

**Comment by ericrayanderson** [comment]
Would it be possible to turn this into a small RE I could for testing?

**Comment by mbacou** [comment]
@ericrayanderson will do in a couple of days. Had to revert back to using standard shiny libs for now.

**Comment by ericrayanderson** [comment]
Okay. Thank you for finding this issue and making me aware.
