### ISSUE TITLE
Reactive Displays and Side Nav Tab

### ISSUE THREAD

**Issue by mattkumar** [ericrayanderson/shinymaterial#30]
Hi,

First, thank you for your hard work and providing us with this wonderful package. I'm currently using it to develop a dashboard. I think I may have stumbled upon a bug. Please correct me if I'm wrong. I noticed that reactive displays do not work on any nav pages, unless it is the first one. Please see the below two examples - I've used the sample code on the package website to illustrate this finding.

#example1 - material_number_box and textOutput work as they should when placed in "example_side_nav_tab_1",

> library(shiny)
> library(shinymaterial)
> 
> 
> ui <- material_page(
>   title = "Basic Page + Side-Nav with Tabs",
>   nav_bar_fixed = TRUE,
> 
>   material_side_nav(
>     fixed = TRUE,
>     
>     material_side_nav_tabs(
>       side_nav_tabs = c(
>         "Example Side-Nav Tab 1" = "example_side_nav_tab_1",
>         "Example Side-Nav Tab 2" = "example_side_nav_tab_2"
>       ),
>       icons = c("cast", "insert_chart")
>     )
>   ),
>   
>   material_side_nav_tab_content(
>     side_nav_tab_id = "example_side_nav_tab_1",
>     tags$h1("First Side-Nav Tab Content"),
> 	 material_number_box(input_id = "ddd", label = "number box", min_value = 5, max_value = 15,initial_value = 10, color = "#ef5350"),
>      textOutput("min_max")		
>   ),
>   material_side_nav_tab_content(
>     side_nav_tab_id = "example_side_nav_tab_2",
>     tags$h1("Second Side-Nav Tab Content")
>  
>   )
> )
> 
> server <- function(input, output) {
>    output$min_max <- renderText({ 
>     paste("You have chosen the number", input$ddd)
>   })
> }
> shinyApp(ui = ui, server = server)

# 
#example2 - material_number_box and textOutput do not work when placed inside "example_side_nav_tab_2",

> library(shiny)
> library(shinymaterial)
> 
> 
> ui <- material_page(
>   title = "Basic Page + Side-Nav with Tabs",
>   nav_bar_fixed = TRUE,
> 
>   material_side_nav(
>     fixed = TRUE,
>     material_side_nav_tabs(
>       side_nav_tabs = c(
>         "Example Side-Nav Tab 1" = "example_side_nav_tab_1",
>         "Example Side-Nav Tab 2" = "example_side_nav_tab_2"
>       ),
>       icons = c("cast", "insert_chart")
>     )
>   ),
> 
>   material_side_nav_tab_content(
>     side_nav_tab_id = "example_side_nav_tab_1",
>     tags$h1("First Side-Nav Tab Content")
>   ),
>   material_side_nav_tab_content(
>     side_nav_tab_id = "example_side_nav_tab_2",
>     tags$h1("Second Side-Nav Tab Content"),
> 
> 	 material_number_box(input_id = "ddd", label = "number box", min_value = 5, max_value = 15,initial_value = 10, color = "#ef5350"),
>      textOutput("min_max")		
>  
>   )
> )
> 
> server <- function(input, output) {
>    output$min_max <- renderText({ 
>     paste("You have chosen the number", input$ddd)
>   })
> }
> shinyApp(ui = ui, server = server)

Best,

**Comment by wangtulao** [comment]
Hello @ericrayanderson,
 
I'm experiencing the same issue as @mattkumar: "reactive displays do not work on any nav pages, unless it is the **first** one".
There is a JS syntax error in the index page: 
![image](https://user-images.githubusercontent.com/1614226/34509908-70c4a1d2-f01d-11e7-9439-c05ea7007001.png)

Thanks for the great package! Looking forwards to the fix. 
Best,
Freeman

**Comment by mattkumar** [comment]
Thanks @wangtulao for echoing the feedback. Interestingly, if you wrap the output in a modal on the secondary nav page, it will work. I'm hoping this gets fixed because I really want to use the dashboard layout :)

**Comment by ericrayanderson** [comment]
Thank you for addressing this issue.

Please try the most recent dev version `devtools::install_github("ericrayanderson/shinymaterial")`.

Let me know if you are still experiencing this issue.
