### ISSUE TITLE
How to seemless Integrate to current shiny on server side?

### ISSUE THREAD

**Issue by harryprince** [ericrayanderson/shinymaterial#33]
I try to using `shinymaterial::material_button(inputId = "query",label = "query")` instead directly `shiny::actionButton(inputId = "query",label = "query")`.

However, it seems shinymaterial cannot replace the same code on the server side.

I suggest that you can checkout shinytheme package, in that, switch web site style is very easy like this:

```
    ,theme = shinythemes::shinytheme("paper")
```

**Comment by ericrayanderson** [comment]
Is your app wrapped in ‘shinymaterial::material_page’?

Is it possible to create a small reproducible example of your issue?

**Comment by harryprince** [comment]
sorry, I found the bug at my code at wrong parameter name

`shinymaterial::material_button(inputId = "query",label = "query")`
should be `shinymaterial::material_button(input_id = "query",label = "query")`
