### ISSUE TITLE
Active material_tab

### ISSUE THREAD

**Issue by TuSKan** [ericrayanderson/shinymaterial#34]
How to determine which of the current tabs is active?

**Comment by charlie86** [comment]
I have the same question! This is an awesome package btw

**Comment by ericrayanderson** [comment]
Currently, there is no built in way to do this. Will be looking into this shortly.

**Comment by charlie86** [comment]
@ericrayanderson 
w00t!!! This is super helpful. Also thanks for making this awesome package. It really helps make apps look more polished

**Comment by jameswcraig** [comment]
> Try the function `side_nav_tabs_info` in the most recent dev version.
> (Usage: `side_nav_tabs_info(input)`, where `input` is the `input` object in the shiny session).
> 
> Dev version install:
> `devtools::install_github("ericrayanderson/shinymaterial")`
> 
> Please let me know if this does not solve your problem or you have any other issues.

Hi @ericrayanderson 

Is there a similar method to view active tab info for a tab created via `material_tabs`? If not, are you aware of any js approach?

As always, thanks for your work on this package 👍 

James
