### ISSUE TITLE
update_material_dropdown requires named vectors as `choices`

### ISSUE THREAD

**Issue by keqiang** [ericrayanderson/shinymaterial#35]
Hi, I've been trying out the `material_dropdown` and it seems when using `update_material_dropdown` on the server side, the `choices` parameter has to be a named vector, otherwise it's rendered incorrectly(maybe it's trying to use the `names` to render). However, this is not mandatory when you use `material_dropdown` on the UI side, which I think is inconsistent. 

Another thing I noticed is that `selected`/`value` is also required in `material_dropdown`/`update_material_dropdown`. I feel it would be more natural if it just defaults to not selecting anything. Especially when I'm initializing an empty drop-down and updating it from the server, I have to specify some dummy values. Also, why this parameter is named `value` here but `selected` in the UI function?

Thanks!

**Comment by ericrayanderson** [comment]
Looking into this. Will get back to this shortly. Thank you for bringing this to my attention.

**Comment by keyurbipinshah** [comment]
Hi,

I'm facing this issue too.

However, on giving names to the 'choice' vector, it works fine.
