### ISSUE TITLE
render leaflet map in material_card

### ISSUE THREAD

**Issue by claire-roberts** [ericrayanderson/shinymaterial#36]
Is it possible to render a leaflet map within a material_card? My attempts have been unsuccessful thus far.

Thanks

**Comment by JimmyG9** [comment]
This (basic) example works for me, but perhaps yours is more complex:

```
# app.R
library(shiny)
library(shinymaterial)
library(leaflet)

ui <- material_page(
  title = "Basic Page + Side-Nav with Tabs",
  nav_bar_fixed = TRUE,
  material_side_nav(
    fixed = TRUE,
    material_side_nav_tabs(
      side_nav_tabs = c(
        "Leaflet" = "example_leaflet"
      ),
      icons = c("insert_chart")
    )
  ),
  material_side_nav_tab_content(
    side_nav_tab_id = "example_leaflet",
    material_card(
      title = "My Map",
      leafletOutput("map", height = 700)
    )
  )
)
server <- function(input, output, session) {
  output$map <- renderLeaflet({
    leaflet() %>%
      addProviderTiles("Stamen.TonerLite",
        options = providerTileOptions(noWrap = TRUE))
  })                           
}
shinyApp(ui = ui, server = server)
```

**Comment by claire-roberts** [comment]
Thanks,
I think I've identified the underlying issue, which is actually with the material_dropdown. When multiple=FALSE the map appears, when multiple=TRUE it does not. An example below:
`
### ui.R ###
library(shiny)
library(shinymaterial)
library(leaflet)

ui <- material_page(
  title = "Basic Page + Parallax",
  # Typically the image will be placed in a folder labeled 'www' 
  # at the same level as the application (server.R & ui.R)
  material_parallax(
    image_source =
      "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8d/Freudenberg_sg_Switzerland.jpg/1920px-Freudenberg_sg_Switzerland.jpg"
  ),
  tags$h1("Page Content"),
  material_row(
    material_column(
    width=3,    
    material_dropdown(
      input_id = "example_dropdown",
      label = "Drop down",
      choices = c(
        "Chicken" = "c",
        "Steak" = "s",
        "Fish" = "f"
      ),
      selected = c("c"),
######### Here is the problem, FALSE works, TRUE doesn't ##############
      multiple = TRUE,
      color = "#ef5350"
    )
    ),
  material_column(
    width=3,
    material_slider(
      input_id = "year_min",
      label = "From Year",
      min_value = 5,
      max_value = 15,
      initial_value = 10,
      color = "#ef5350"
    )
    )
    ),
  
  material_row(
    material_column(
      width=9,
  material_card(
    title = "My Map",
    leafletOutput("map", height = 700)
  )),
  material_column(
    width=2,
    material_card(
      title="",
      depth=4,
      material_switch(
        input_id = "hapc",
        label = "HAPCs",
        off_label = "",
        on_label = ""
      ),
      material_switch(
        input_id = "pres",
        label = "Presence only",
        off_label = "",
        on_label = ""
      ),
      material_radio_button(
        input_id = "plot_theme",
        label = "Theme",
        choices = 
          c("Default" = "default",
            "Classic" = "classic",
            "Light" = "light",
            "Dark" = "dark")
      )
      )
    )
  ))

### server.R ###
server <- function(input, output, session) {
  output$map <- renderLeaflet ({
    leaflet() %>% 
      addTiles() %>%  # Add default OpenStreetMap map tiles
      addMarkers(lng=174.768, lat=-36.852, popup="The birthplace of R")
  })                          
}
`

**Comment by ericrayanderson** [comment]
Claire,
Thank you for making me aware of this issue. I put a fix in, please try the most recent dev version
`devtools::install_github("ericrayanderson/shinymaterial")`.

Jimmy, thank you for trying to remedy the issue. It was something that needed to be changed fairly deep w/in in the package.

**Comment by claire-roberts** [comment]
Works great now. Thanks!
