### ISSUE TITLE
shiny dashboard tabsetPanel equivalent in shinymaterial?

### ISSUE THREAD

**Issue by sunitgk** [ericrayanderson/shinymaterial#39]
I'm defining tab-content via shiny modules. 

#### Here's the UI piece of code: 

`
dashboardBody(

           tabsetPanel(id = "all_data",
                  tabPanel("A", TS_module_UI("license")),
                  tabPanel("B", TS_module_UI("upgversion")),
                  tabPanel("C", TS_module_UI("all"))
 )`
 
#### The server piece calls the module:

           `callModule(TS_module,` "license", data = list(all_data, lic),  rev_type = "A", prod_group, x, y, show_data)`

#### Here's a piece of module. R that defines where the contents of the tabs go.

` TS_module_UI <- function(id) {
              ns <- NS(id)
             
    tagList(
         fluidRow(
         valueBoxOutput(ns("tile_1")),
        valueBoxOutput(ns("tile_2")),
        `valueBoxOutput(ns("tile_3"))` ),

    fluidRow(
      box(highchartOutput(ns("hcontainer4"))),
      box(highchartOutput(ns("hcontainer5")))
    )`

       

#### Is there an equivalent of the tabsetPanel in Shiny material? If not, any pointers as how to with the existing shiny material tabs functions?

`material_tabs(
    tabs = c(
      "First Tab" = "first_tab",
      "Second Tab" = "second_tab"
    )
  ),
  material_tab_content(
    tab_id = "first_tab",
    tags$h1("First Tab Content")
  ),
  material_tab_content(
    tab_id = "second_tab",
    tags$h1("Second Tab Content")
  )
)`

**Comment by ericrayanderson** [comment]
Is it possible to create a small app with an example of what your trying to do here? I could then try to re-create that behavior with `shinymaterial`

**Comment by sunitgk** [comment]
Thanks Eric. I've added you as a collaborator https://github.com/sunitgk/shiny_material_modules/invitations

**Comment by jpzhangvincent** [comment]
just curious, so do we have a "tabsetPanel" in Shiny material?
