### ISSUE TITLE
Allow to define which color theme to use

### ISSUE THREAD

**Issue by happyshows** [ericrayanderson/shinymaterial#4]
Hi,

for example, I'd like to switch to blue lighten-2 from the default red theme, but I don't find a easy way to do so unless I figure out all the divs needs to be changed and manually override them.
Is there any way to switch in one line of code?

**Comment by ericrayanderson** [comment]
This is a feature I had implemented at one point. I think I am going to put it back in.

**Comment by ericrayanderson** [comment]
Is there a specific input where this would be useful? I am planning on adding the functionality to all inputs.

On a side note, is the input function (e.g. `material_input(type = 'button')`, etc.) convention useful, vs each input having its own function (e.g. `material_button()`, etc.).

**Comment by happyshows** [comment]
I think your struggle is with standardization vs expressiveness of the function name. In my experience with other shiny related packages, people use the 2nd approach more often. In my opinion, separating them may also allow other people to extend the function easier. My 2 cents.

**Comment by ericrayanderson** [comment]
Check out v0.2.1 on CRAN - inputs now have a 'color' parameter.
