### ISSUE TITLE
Customize text in Close button Modal

### ISSUE THREAD

**Issue by Morais14** [ericrayanderson/shinymaterial#40]
Is there possible to change the text in modal close button? The default it's "close", i need put in portuguese, "Fechar".

Sometthing like this:

```
material_modal(
   modal_id = "example_modal",
   button_text = "Modal",
   **button_close_text = "Fechar"**,
   button_icon = "open_in_browser",
   title = "Showcase Modal Title",
   tags$p("Modal Content")

 )
```
Many thanks!

**Comment by ericrayanderson** [comment]
Try the latest dev version:
`devtools::install_github("ericrayanderson/shinymaterial")`

Theres a new paramete `close_button_label` in the function `material_modal`.

Please let me know if you run into issues or this doesn't solve your problem.

**Comment by Morais14** [comment]
Thanks a lot! Works fine!
