### ISSUE TITLE
Initialize material_dropdown without choices

### ISSUE THREAD

**Issue by mturbasa** [ericrayanderson/shinymaterial#41]
Hi, it would be really great if the `material_dropdown` input could be initialized without choices. It is possible in shiny: `shiny::selectInput(inputId = "id", label = "label", choices = NULL)`.

I also find the existing documentation a little bit inconsistent: `material_dropdown` has only two mandatory parameters - `input_id` and `label`, others are `NULL` by default. However creating this input with only those two parameters throws an error:
`> shinymaterial::material_dropdown(input_id = "id", label = "label")`
`Error in material_option_tag_list[[i]] <- shiny::HTML(paste0("<option",  : 
  attempt to select less than one element in integerOneIndex`

**Comment by ericrayanderson** [comment]
I see your point about that being inconsistent, looking into fixing this.

**Comment by ericrayanderson** [comment]
Fixed
