### ISSUE TITLE
Options for internationalization in material_date_picker

### ISSUE THREAD

**Issue by mturbasa** [ericrayanderson/shinymaterial#42]
Hi,  it would be really great if more options for the `material_date_picker` input could be specified. I mean internationalization options especially (date format, language etc.), either with a language abbreviation (like in `shiny::dateInput`) or with a list of JavaScript parameters for materializecss.css (like in `DT::datatable`).

**Comment by ericrayanderson** [comment]
OK, good suggestion, looking into this.

**Comment by fvermeij** [comment]
I found a pretty hacky  solution to this by actually changing the source code of the shinymaterial package, specifically the 'shiny-material-date-picker.js' file. That contains `$(.datepicker').pickadate({})`

You can edit that and give options to it [http://amsul.ca/pickadate.js/date/](documentation here).

For example: `$(.datepicker').pickadate({monthsFull: ['Januari', 'Februari', etc})` for dutch months.
