### ISSUE TITLE
Adding image to navbar/title

### ISSUE THREAD

**Issue by mgahan** [ericrayanderson/shinymaterial#43]
Awesome package! I am curious if it is possible to add an image to the title of a material page? Something like a company/organizational logo.

I have tried something like this, but not really working like I had hoped.

```
ui <- material_page(
  title = c("My Title",img(src = "img/material.png", height = 50, width = 100))
)
```

Is this some way around this? Is there a way to remove the navbar on a `material_page` and add a `material_card` that could do this?

Thanks so much

**Comment by ericrayanderson** [comment]
Try the most recent dev version, it allows for no including the nav bar
`material_page(include_nav_bar = FALSE, ...)`

`devtools::install_github("ericrayanderson/shinymaterial")`
