### ISSUE TITLE
I can't use a normal ModelDialogue Box

### ISSUE THREAD

**Issue by vikram-rawat** [ericrayanderson/shinymaterial#45]
I need to open up a dialogue box only when there is something wrong with data it is not dependent on any button. I can't use material model for this purpose and some how I can't use default modeldialogue of shiny as well. Please help me..

**Comment by ericrayanderson** [comment]
Please try the most recent dev version.

Function to open modal: `open_material_modal()`
Parameter in `material_modal` to hide the button: `display_button`

`devtools::install_github("ericrayanderson/shinymaterial")`
