### ISSUE TITLE
Tabs have scroll bar

### ISSUE THREAD

**Issue by tjwieg** [ericrayanderson/shinymaterial#48]
I'm making an app with 3 tabs, and when I switch from the second (middle) tab to the third (right) tab, a scroll bar appears on my tab row, as in this screenshot:
![Example of the scroll bar in my app, Starshiny](https://i.imgur.com/AE1exVr.png)

Interestingly, when I tried to make a minimum reproducible example, such as this:
```
require("shiny")
require("shinymaterial")

ui <- material_page(
  title = "Example of Bug #48",
  include_fonts = TRUE,
  material_tabs(tabs = c("Upload Data" = "first",
                         "Data Analysis" = "second",
                         "About" = "third")
                ),
  material_tab_content(tab_id = "first",
                       material_row(material_card(title = "This is the first tab!"))),
  material_tab_content(tab_id = "second",
                       material_row(material_card(title = "This is the second tab!"))),
  material_tab_content(tab_id = "third",
                       material_row(material_column(
                         HTML(
                           "Notice that if you switch from the second tab to this one, a scroll bar appears on the tab row."
                         )
                       )))
)

server <- function(input, output) {
  
}

shinyApp(ui = ui, server = server)
```

It doesn't have the scrollbar:
![Example doesn't have the scroll bar!](https://i.imgur.com/4wYoaMi.png)

I'm not sure why this is happening to my app and not the example I came up with. My code is available for review at: https://github.com/rbotts/OverlapAnalysis/tree/a788ad1fca6265c914a78c8f77d452562c65408c/Starshiny

Here's a summarized/condensed version of my app's ui.R:
```
colHex <- "#f4511e"
colText <- "deep-orange darken-1"

#Page ----
material_page(
  title = "Starshiny: Overlap Analysis with R Shiny",
  nav_bar_color = colText,
  
  material_tabs(
    tabs = c("Upload Data" = "upload",
             "Data Analysis" = "analysis",
             "About" = "about")
    ),
  
  #Upload tab ----
  material_tab_content(tab_id = "upload",
    #two columns, one with some text and one with a card with a material_file_input
    ),
  
  #Data Analysis tab ----
  material_tab_content(
    tab_id = "analysis",
    material_row(
      #three columns with various cards on them
    )
  ),
  
  #About tab ----
  material_tab_content(
    tab_id = "about",
    
    material_row(
      material_column(
        width = 12,
        HTML(instructions)
      )
    )
  )
)
```
Rather puzzlingly, even that stripped-down version doesn't have the scroll bar appear. I'm pretty lost as to what exactly is causing the bug, but perhaps someone else can figure it out?

**Comment by pommedeterresautee** [comment]
I have the same issue, and same solution, the second clicks slightly move the moving bar highlighting the selected tab, and the scroll bar disappear, meaning, it s the wrong position of the moving bar after the first click on a tab which causes the scroll bar appearance.
