### ISSUE TITLE
ReactiveUI and `if` statements

### ISSUE THREAD

**Issue by tjwieg** [ericrayanderson/shinymaterial#49]
### Background
I was trying to make an app in which you use a `material_switch` to turn on/off a `reactiveUI` item (containing a `material_dropdown`). However, this breaks the `material_dropdown`. When it is supposed to show, only the label appears (and in full size text rather than the smaller label text expected).

### Minimum working example:
```
require("shiny")
require("shinymaterial")

ui <- material_page(
  title = "Reactive UI and \"if\" Statements",
  material_row(
    material_column(
      width = 6,
      material_switch(
        input_id = "oneTwo",
        label = NULL,
        off_label = "One Option",
        on_label = "Two Options",
        initial_value = TRUE
      ),
      material_dropdown(input_id = "selectA",
                        label = "Choice A",
                        choices = c("First Choice" = "choice1",
                                    "Second Choice" = "choice2",
                                    "Third Choice" = "choice3"))
    ),
    material_column(
      width = 6,
      uiOutput(outputId = "selectB")
    )
  )
)

server <- function(input, output) {
  output$selectB <- renderUI({
    if (input$oneTwo) material_dropdown(input_id = "selectB",
                                        label = "Choice B",
                                        choices = c("First Choice" = "choice1",
                                                    "Second Choice" = "choice2",
                                                    "Third Choice" = "choice3"))
  })
}

shinyApp(ui = ui, server = server)
```

### Some screenshots:
![Working appropriately (switched off)](https://i.imgur.com/XPnmX4X.png)
-  -  -  -  -
![It's broken!](https://i.imgur.com/KmoXjNk.png)

**Comment by tjwieg** [comment]
I realized that I was making a syntax error in how I was setting this up. I expected to be able to do as I did above, doing `renderUI({if (bool1) material_element_1() else material_element_2()})`, but the proper way to format this is `renderUI(if (bool 1) {material_element_1()} else {material_element_2()})`.

**Comment by steve-liang** [comment]
@tjwieg I tried to put if statement outside of {} and still seeing the same issue with only label got rendered. Did you happen to find a fix? or other way of coding it?

Thanks!

**Comment by tjwieg** [comment]
> @tjwieg I tried to put if statement outside of {} and still seeing the same issue with only label got rendered. Did you happen to find a fix? or other way of coding it?
> 
> Thanks!

I don't think so, @steve-liang , sorry. I'm pretty sure I posted all my findings in this thread (above). Best of luck figuring things out, though!
