### ISSUE TITLE
renderUI issue

### ISSUE THREAD

**Issue by jyjek** [ericrayanderson/shinymaterial#51]
Hi!
`id2` input didn't work, but ok with `selectizeInput`

    library(shiny)
    library(shinymaterial)

    ui <- material_page(
      title = "Basic Page",
      uiOutput("AT"),
      uiOutput("AT2")  
    )

    server <- function(input, output) {  
     output$AT<-renderUI({
    material_dropdown(input_id="id", label="ID-1",
                      choices = list("1" = "One", "2" = "Two"),multiple=F)
     })
     output$AT2<-renderUI({    
    material_dropdown(input_id="id2", label="ID-2",
                      choices = list("A" = "A", "B" = "B"),multiple=F)
     })
    }
    shinyApp(ui = ui, server = server)

**Comment by lisovyk** [comment]
One of the elements misses the `<script> ... </script>` part, looking from dev tools.
Interestingly enough, if you rename the outputs to 'A1' and 'B1' the bug goes to the second element. I wonder if it has something to do with numbers in output names.

**Comment by MehranMoghtadai** [comment]
Having the same issue. And not just using renderUI. I also get it if I just put two material_dropdowns but in different tabs directling in the ui.

**Comment by bilbaoba** [comment]
The problem come from the ``` $('.shiny-material-dropdown').material_select();``` javascript command is launch only on document ready. So for the dropdown in the ui or only for the first ajax call from renderUI...

**Comment by bilbaoba** [comment]
Hi everyone, 

This issue is clearly a bug (@ericrayanderson can you put the label on it :smile: ) who clearly not allow usage of `material_dropdown` with dynamics UI. 

I tried to solve it but I don't find elegant way to solve this problem.  

It will be great we find solution for the next release of the package, I continue my research. 

Regards

**Comment by ericrayanderson** [comment]
Fixed with update to materialize (coming out in next version).

**Comment by steve-liang** [comment]
With the latest update, it resolves the prior issue but putting additional condition for some reason doesn't work. 

```
library(shiny)
library(shinymaterial)

ui <- material_page(
  title = "Basic Page",
  uiOutput("AT"),
  uiOutput("AT2"),
  
  br(),
  br(),
  actionButton("btn", label='click')
)

server <- function(input, output) {  
  output$AT<-renderUI({
    material_dropdown(input_id="id", label="ID-1",
                      choices = list("1" = "One", "2" = "Two"),multiple=F)
  })
  output$AT2<-renderUI({  
    
    if(input$btn > 2 & input$btn < 5){
    material_dropdown(input_id="id2", label="ID-2",
                      choices = list("A" = "A", "B" = "B"),multiple=F)
      # selectizeInput(inputId="id2", label="ID-2",
      #                   choices = list("A" = "A", "B" = "B"),multiple=F).  # select/izeInput will work
    }
  })
  observe({
    print(input$btn)
  })
}
shinyApp(ui = ui, server = server)
```

Really like this pkg for the simplicity. Just want to thank you for continuing updating it!

**Comment by garthtarr** [comment]
Related to this, if you have a material_dropdown in two tabs, with data reactive choices, one of them doesn't work.

For example, this does NOT work:

```
library(shiny)
library(shinymaterial)
library(dplyr)

# Wrap shinymaterial apps in material_page
ui <- material_page(
  title = "Basic Page + Side-Nav with Tabs",
  nav_bar_fixed = TRUE,
  # Place side-nav in the beginning of the UI
  material_side_nav(
    fixed = TRUE,
    # Place side-nav tabs within side-nav
    material_side_nav_tabs(
      side_nav_tabs = c(
        "Example Side-Nav Tab 1" = "example_side_nav_tab_1",
        "Example Side-Nav Tab 2" = "example_side_nav_tab_2"
      ),
      icons = c("cast", "insert_chart")
    )
  ),
  # Define side-nav tab content
  material_side_nav_tab_content(
    side_nav_tab_id = "example_side_nav_tab_1",
    uiOutput("ddA")
    
  ),
  material_side_nav_tab_content(
    side_nav_tab_id = "example_side_nav_tab_2",
    uiOutput("ddB")
  )
)

server <- function(input, output) {
  
  output$ddA = renderUI({
    material_dropdown(input_id = "pageA", label = "First selection",
                      choices = mtcars %>% select(cyl) %>% distinct() %>% pull())
  })
  
  output$ddB = renderUI({
    material_dropdown(input_id = "pageB", label = "Second selection",
                      choices = mtcars %>% select(gear) %>% distinct() %>% pull())
  })
}
shinyApp(ui = ui, server = server)
```

but this does work:

```
library(shiny)
library(shinymaterial)
library(dplyr)

# Wrap shinymaterial apps in material_page
ui <- material_page(
  title = "Basic Page + Side-Nav with Tabs",
  nav_bar_fixed = TRUE,
  # Place side-nav in the beginning of the UI
  material_side_nav(
    fixed = TRUE,
    # Place side-nav tabs within side-nav
    material_side_nav_tabs(
      side_nav_tabs = c(
        "Example Side-Nav Tab 1" = "example_side_nav_tab_1",
        "Example Side-Nav Tab 2" = "example_side_nav_tab_2"
      ),
      icons = c("cast", "insert_chart")
    )
  ),
  # Define side-nav tab content
  material_side_nav_tab_content(
    side_nav_tab_id = "example_side_nav_tab_1",
    material_dropdown(input_id = "pageB", label = "Second selection",
                      choices = c("A","B"))
    
  ),
  material_side_nav_tab_content(
    side_nav_tab_id = "example_side_nav_tab_2",
    material_dropdown(input_id = "pageA", label = "First selection",
                      choices = c(1,2))
  )
)

server <- function(input, output) {

  
}
shinyApp(ui = ui, server = server)
```

Any help to fix this would be very welcome!

**Comment by jameswcraig** [comment]
Hi @ericrayanderson I'm really loving your shinymaterial package but really need to dynamically generate dropdown inputs using uiOutput, however as mentioned above, using uiOutput + renderUI indeed does NOT work. Any updates on this?

**Comment by ericrayanderson** [comment]
@jameswcraig 

Is it just within tabs you experience this issue? Or renderUI on a static page does not work as well?

**Comment by ericrayanderson** [comment]
@steve-liang @garthtarr @jameswcraig 

Try the dev version via `remotes::install_github("ericrayanderson/shinymaterial")`

The new functions are: `render_material_ui()` & `material_ui_output()`

**Comment by garthtarr** [comment]
That seems to have fixed it, sorry for overcomplicating the problem with multiple tabs, seems like the issue was entirely to do with the renderUI() function.

**Comment by jameswcraig** [comment]
Thanks @ericrayanderson, the functions you provided in the dev version work nicely :) 

On a side note, are you planning to support accordion/expansion panels in ```shinymaterial```? I'm currently having to utilize ```bs4Dash::bs4Accordion()``` to collapse panels (```shinyDashboardPlus::accordion()``` creates strange black box on screen occasionally, while ```bs4Dash::bs4Accordion()``` does appear to be compatible with ```material_page()```)

However, it'd be great to have functionality  in ```shinymaterial``` to collapse ```material_card()``` - thanks again for you hard work on this package!

**Comment by jameswcraig** [comment]
Hi @ericrayanderson after further testing it appears there is still an issue.  Inputs initialize ok but do not dynamically generate new inputs based on selections of other inputs.  I've provided a reprex below;  based on selections in "Tab 1",  you can see the expected behavior for the ```textInput()`` using ```uiOutput()``` + ```renderUI``` in "Tab 2" works fine (the ```textInput()``` also materializes nicely btw), however, the ```material_dropdown()``` input using ```material_ui_output()``` + ```render_material_ui()```  will initialize the inputs correctly in Tab 2 (using default selections in Tab 1, or if selections are changed in Tab 1 without first clicking on Tab 2), but the ```material_dropdown()``` inputs in Tab 2 do not update after going back to Tab 1 and changing selections.  Any idea what the issue may be? See reprex below:

```
library(shiny)
library(shinymaterial)
library(shinyjs)

ui <- material_page(
  useShinyjs(),
  title = "render_material_ui() Example",
  nav_bar_fixed = TRUE,
  
  material_tabs(tabs = c(
    "Tab 1" = "tab_1",
    "Tab 2" = "tab_2")
  ),
  
  material_tab_content(
    tab_id = "tab_1",
    material_card(
      title = "Tab 1",
      material_dropdown(input_id = "names_1", 
                        label = "Names selection",
                        choices = c("A","B", "C", "D"), 
                        selected = c("A", "B"),
                        multiple = TRUE))
  ),
  material_tab_content(
    tab_id = "tab_2",
    material_card(
      title = "Tab 2",
      h4("This Doesn't Work"),
      material_ui_output("out_1"),
      h4("This Works"),
      uiOutput("out_2")
    )
   )
  )


server <- function(input, output) {
  
  
  render_dropdown <- function(input){
    r <- vector(mode = "list", length = length(input))
    for (i in seq_along(input)) {
      r[[i]] <- tagList( 
        material_dropdown(input_id = paste0(input[[i]], "_dropdown"),
                          label = paste0(input[[i]]), 
                          choices = c("Choice 1", "Choice 2", "Choice 3")
        )
      )
    }
    r
  }
  
  render_text <- function(input){
    r <- vector(mode = "list", length = length(input))
    for (i in seq_along(input)) {
      r[[i]] <- tagList(
        textInput(inputId  = paste0(input[[i]], "_text"),
                          label = paste0(input[[i]]),
                          value = paste0(input[[i]])
        )
      )
    }
    r
  }
 
  
  test_dropdown <- reactive({
    l <- render_dropdown(input$names_1)
    l
  })
  
  test_text <- reactive({
    l <- render_text(input$names_1)
    l
  })
  
  output$out_1 <- render_material_ui({
      test_dropdown()
  })
  
  output$out_2 <- renderUI({
      test_text()
  })
}
  


shinyApp(ui = ui, server = server)
```

**Comment by ericrayanderson** [comment]
@jameswcraig 

Thanks for testing this in depth.

The issue you found needs to addressed slightly differently than that first approach.

Can you try the newest GitHub version, but with these adjustments your app above:

- Change `material_ui_output` back to `uiOutput`
- Change `render_material_ui ` back to `renderUI`
- Wrap `test_dropdown()` within the new function `render_material_from_server`

E.g. 
changes in ui.R
` uiOutput("out_1")`

changes in server.R
```
 output$out_1 <- renderUI({
    render_material_from_server(
          test_dropdown()
     )
  })
```

**Comment by jameswcraig** [comment]
@ericrayanderson This seems to work!  Thanks again for being so prompt with the responses and fixes, I really appreciate your efforts.

**Comment by jameswcraig** [comment]
Hi @ericrayanderson, on a related topic, do you know if shinymaterial is compatible with ```shiny::insertUI()``` and ```shiny::removeUI()```?  The ```material_dropdown()``` does not render as expected, although the ```shiny::textInput()``` does render as expected (and materializes).

See reprex below:

```
library(shiny)
library(shinymaterial)
library(shinyjs)
# function to render UI element

renderMaterialElements <- function(id, nameDef) {
  
  material_card(
    material_button(paste0("rmBtn", id), label = "", icon = "delete"),
    material_dropdown(paste0("dropdown", id), label = paste("Item", id), choices = c("A", "B", "C")),
    textInput(paste0("name", id), label = paste("Item", id))
  )

}


server <- function(input, output, session) {
  
  
  # on "Add" button click: 
  counter <- 0
  observeEvent(
    input$addBtn,
    {
      counter <<- counter +1
      insertUI(
        selector = '#container',
        where = "beforeEnd",
        ui = renderMaterialElements(
           id = paste0("ui",counter),
           nameDef = "New Text"
         ),
        session = session
      )
    },
    ignoreNULL = TRUE,
    ignoreInit = TRUE
  )
  
  
  
  output$container <- renderUI({
    render_material_from_server(
    div()
    )
  })
  
}

ui <- material_page(
  useShinyjs(),
  titlePanel("Dynamically Add/Remove UI Elements"),
  hr(),
  material_button("addBtn", "Add"),
  br(),br(),
  uiOutput("container")
)

shinyApp(ui, server)
```

**Comment by chriswweibo** [comment]
> Hi @ericrayanderson, on a related topic, do you know if shinymaterial is compatible with `shiny::insertUI()` and `shiny::removeUI()`? The `material_dropdown()` does not render as expected, although the `shiny::textInput()` does render as expected (and materializes).
> 
> See reprex below:
> 
> ```
> library(shiny)
> library(shinymaterial)
> library(shinyjs)
> # function to render UI element
> 
> renderMaterialElements <- function(id, nameDef) {
>   
>   material_card(
>     material_button(paste0("rmBtn", id), label = "", icon = "delete"),
>     material_dropdown(paste0("dropdown", id), label = paste("Item", id), choices = c("A", "B", "C")),
>     textInput(paste0("name", id), label = paste("Item", id))
>   )
> 
> }
> 
> 
> server <- function(input, output, session) {
>   
>   
>   # on "Add" button click: 
>   counter <- 0
>   observeEvent(
>     input$addBtn,
>     {
>       counter <<- counter +1
>       insertUI(
>         selector = '#container',
>         where = "beforeEnd",
>         ui = renderMaterialElements(
>            id = paste0("ui",counter),
>            nameDef = "New Text"
>          ),
>         session = session
>       )
>     },
>     ignoreNULL = TRUE,
>     ignoreInit = TRUE
>   )
>   
>   
>   
>   output$container <- renderUI({
>     render_material_from_server(
>     div()
>     )
>   })
>   
> }
> 
> ui <- material_page(
>   useShinyjs(),
>   titlePanel("Dynamically Add/Remove UI Elements"),
>   hr(),
>   material_button("addBtn", "Add"),
>   br(),br(),
>   uiOutput("container")
> )
> 
> shinyApp(ui, server)
> ```

Same issue with me.

I put material_dropdown and material_text_box in the insertUI.
Only the latter is rendered.
Hope somebody could provide a walkaround or a direct solution.
