### ISSUE TITLE
No Roboto Fonts in shinyapps.io from Iphone

### ISSUE THREAD

**Issue by anapaularg** [ericrayanderson/shinymaterial#57]
Hi,

I've developed a shiny app using shinymaterial, when I host in shinyapps.io and then open the app from my **iphone**, everything is ok but the Roboto Fonts.

In `material_page` I set the parameter `include_fonts = TRUE`.

Is there any additional steps to take in order to see the Roboto fonts?

**Comment by ericrayanderson** [comment]
There should not be any additional steps. Are you using safari browser on iPhone?
I am wondering if it is a safari vs chrome issue. Potential tests:

1. Have you tried your app in a safari browser on a computer?
2. Have you tried your app in a chrome browser on your iPhone?

Testing those scenarios may help solve the issue, in the meantime I will check on the backend for potential reasons.

**Comment by Kvit** [comment]
I have guess why this may happen.  / shiny-material-page.R  is trying to create local /www... folder and copy fonts there. But depending on how shiny server is installed the application (which is shiny user) may not have write permissions to create the local folder - typically those permissions are for root user only.  
--------------
The solution would be : try to create local dir and copy resources, if (error)  pull resources from CDN

**Comment by Kvit** [comment]
I also found another problem: the application is trying to place fonts to the folder `/www/fonts/..` but it  looking for fonts in folder `/fonts/..` relative to server root (not '/www/fonts')  the workaround for this problem is to place 'fonts/..' folder at the root of the server manually.
