### ISSUE TITLE
Recolor hamburger button of side_nav

### ISSUE THREAD

**Issue by fvermeij** [ericrayanderson/shinymaterial#58]
I'm currently making an application in shinymaterial, and our designed decided that the nav bar needs to be white. I actually agree it looks quite nice, but now the problem is that you can't see the hamburger button anymore. Here is an image to illustrate the issue:

https://i.imgur.com/E966qtx.png

Is there any way to recolor the hamburger button? I don't really care if it becomes an official option, even a hacky option would be fine with me. But if it's an actual option in the material_page function, all the better.

**Comment by ericrayanderson** [comment]
Try adding a css tag to the head to adjust the color of the collapse button, e.g.:

 `material_page(`
`title = "Example App", `
`tags$head(tags$style(".button-collapse{color:black}")),`
` ...`

Change `black` to whatever color you prefer (css or hex)

**Comment by fvermeij** [comment]
Thanks a lot! That worked perfectly, thanks! Great package by the way, I got a lot of compliments from my colleagues who didn't believe that I used R :)
