### ISSUE TITLE
Space between text in choices

### ISSUE THREAD

**Issue by Rhoboot** [ericrayanderson/shinymaterial#6]
Hello,

Begin testing this package a few days ago, note that I have problems with variables where there is a space between the possible values of a category.

For example:

Choices = c ("A" = "A Juice",
"B" = "B Juice",
"C" = "C Juice"),

The output from input $ only brings the first part of the text.

Attached code Example.

```library(shiny)
library(shinymaterial)
ui<-material_page(
        title = "test",
        tags$br(),
        material_row(
                material_column(
                        width = 3,
                        material_card(
                                title = "",
                                depth = 2,
                                material_dropdown(
                                        input_id = "example_dropdown",
                                        label = "Test Dropdown Input",
                                        choices = c(
                                                "AJ" = "A Juice",
                                                "BJ" = "B Juice",
                                                "CJ" = "C Juice"
                                        ),
                                        selected = "A Juice"
                                        )
                                ),
                        material_column(
                                width = 9,
                                material_card(
                                        title = "Text Output",
                                        depth = 4,
                                        textOutput("text1")
                                )))))

server<-function(input, output) {
        output$text1<-renderText(input$example_dropdown)  
}

shinyApp(ui = ui, server = server)
```

regards

Robert

**Comment by ericrayanderson** [comment]
Would reverse the order solve your issue?

I.e.,

    c("A Juice" = "AJ",
      "B Juice" = "BJ",
      "C Juice" = "CJ")
rather than

    c("AJ" = "A Juice",
      "BJ" = "B Juice",
      "CJ" = "C Juice")

The names of the vector is the display name, and the values are the underlying values that get sent to the server.

If this solution does not work for your case let me know.

**Comment by Rhoboot** [comment]
It does not work, because the server receives incomplete information.

For this other case if you selected "A Juice" the server receives "A"

```
choices = c("A Juice" = "A Juice",
                     "B Juice" = "B Juice",
                     "C Juice" = "C Juice")
```

<img width="485" alt="screenshot of safari 5-3-17 01-14-28" src="https://cloud.githubusercontent.com/assets/7344313/25648097/7fc7d3ce-2f9e-11e7-82c3-f808cec7cc7c.png">

**Comment by ericrayanderson** [comment]
Try the dev version:

    devtools::install_github("ericrayanderson/shinymaterial")

If this fix works, I will include it the next time I post an update to CRAN.

**Comment by Rhoboot** [comment]
Excellent, now work!

Thank.

**Comment by ericrayanderson** [comment]
does being able to add one space suffice?

**Comment by lisovyk** [comment]
It does not. It should work with infinite spaces in theory, not just one.

**Comment by ericrayanderson** [comment]
Try loading the dev version
    devtools::install_github("ericrayanderson/shinymaterial")
It should now at least have the same behavior as "selectInput"

**Comment by Rhoboot** [comment]
Okay, now it really works as expected.
