### ISSUE TITLE
Next and previous button for material_tab 

### ISSUE THREAD

**Issue by Kaiwenteoh** [ericrayanderson/shinymaterial#68]
Hi,

First of all, thank you for your package and helpful documentation.

Currently, I have faced some issue on the material_tab which is if I could make 'Next' and 'Previous' button on each tab of material_tab to allow users to move to the next tab. 

Is it possible to do that?

Thank you

**Comment by pommedeterresautee** [comment]
You would need to call select method as described here (https://materializecss.com/tabs.html) but so far it doesn't work for me :-(

```R
session$sendCustomMessage(
                   type = "shinymaterialJS",
                   "$('#TAB_ID').tabs('select');"
                 )
```

**Comment by pommedeterresautee** [comment]
With this PR it s doable : https://github.com/ericrayanderson/shinymaterial/pull/81

**Comment by Kaiwenteoh** [comment]
> With this PR it s doable : #81

Tq for letting me know.
