### ISSUE TITLE
Can't select a radiobutton with no value

### ISSUE THREAD

**Issue by lisovyk** [ericrayanderson/shinymaterial#7]
```
library(shinymaterial)

ui <- material_page(
    material_radio_button(
    input_id = "upload_quote",
    "Quote:",
    choices = list(
        "None" = "",
        "Double Quote" = '"',
        "Single Quote" = "'"
    )
    )
)

server <- function(input, output) {}

shinyApp(ui = ui, server = server)
```

I'm trying to make a selector for csv uploader through shinymaterial. With the code attached here one can't check the first option.

**Comment by lisovyk** [comment]
Is shinymaterial even alive?

**Comment by ericrayanderson** [comment]
Try loading the dev version

    devtools::install_github("ericrayanderson/shinymaterial")

It should solve the issue - let me know if this fix does not address your problem.

**Comment by lisovyk** [comment]
Hi! I've already bypassed that moment in original app. Though I can't reproduce it now with the example above, so maybe it worked.
