### ISSUE TITLE
Feature Request:  Add selected choice to material_radio_button

### ISSUE THREAD

**Issue by Kvit** [ericrayanderson/shinymaterial#74]
material_radio_button control is missing selected choice e.g. radioButtons(inputId, label, choices = NULL, **selected = NULL**,).  Sometimes it is nessesary to have specific choice selected or none selected. 
Related to issue #38

**Comment by bilbaoba** [comment]
Hi Vitali, 

Not sure it's possible. Eric never indicate in his code witch one is checked. 

If you enter :

```R
material_radio_button(input_id = "test", label = "label", choices = 1:2)
```

it return ;

```html
<form action="#" id="test" class="shiny-material-radio-button">
  <label for="test">label</label>
  <p>
    <input type="radio" name="test" class="" id="1"/>
    <label for="1">1</label>
  </p>
  <p>
    <input type="radio" name="test" class="" id="2"/>
    <label for="2">2</label>
  </p>
</form>
<div></div>
```

If you look at the documentation there : https://materializecss.com/radio-buttons.html; it seem you can indicate witch on is selected with the tag `checked` (also some cool feature like `disabled`), but if you put nothing, the first one will be automatically selected (like hire with Eric code). 

Maybe consider for your usage `material_checkbox` and some server code to uncheck if you check another option. 

I will soon post a PR with implementation of `selected` for `material_radio_button` function.

Regards

**Comment by Kvit** [comment]
Thank you very much, indeed I have seen `selected ` option in `materializecss.com/radio-buttons`  and if this feature is implemented with the ability to update `selected ` choice from the server side it should solve the problem.

**Comment by bilbaoba** [comment]
@Kvit, you can close if it answer to your request.
