### ISSUE TITLE
How can we open a tab programatically

### ISSUE THREAD

**Issue by pommedeterresautee** [ericrayanderson/shinymaterial#79]
I am looking for a way to set a open / select a tab programatically.
Here is the materialize commands : https://materializecss.com/tabs.html
Any idea on how to do it from R?

**Comment by bilbaoba** [comment]
Hi Pomme De Terre Sautée! 

You can use a Javascript call like : 
```javascript
$('li.tab a[href$="#idOfyourTab"]:first').trigger("click");
```
This is an example into an app :

```R
library(shiny)
library(shinymaterial)

ui <- material_page(
  title = "Basic Page + Side-Nav + Tabs",
  material_side_nav(fixed = FALSE, tags$h3("Side-Nav Content")),
  material_tabs(
    tabs = c( "First Tab" = "first_tab", "Second Tab" = "second_tab")
  ),
  material_tab_content(
    tab_id = "first_tab", 
    material_button(input_id = "button", label = "GO TO SECOND TAB")
  ),
  material_tab_content(
    tab_id = "second_tab", 
    tags$h1("Second Tab Content")
  )
)

server <- function(input, output, session) {
  observe(
    {
      if (input$button == 0) return()
      js_code <- "$('li.tab a[href$=\"#second_tab\"]:first').trigger(\"click\");"
      session$sendCustomMessage(type = "shinymaterialJS", js_code)  
    }
  )
  
}

shinyApp(ui = ui, server = server)
```

Also I can make generic R function into a PR to do that but I'm not sur @ericrayanderson want this feature. Let him answer us about this type functionality into shinymaterial.  

This function can also enable/disable programmatically a tab for example.
We can get some inspiration from the Shiny package : https://github.com/rstudio/shiny/blob/master/R/insert-tab.R

Regards.

**Comment by pommedeterresautee** [comment]
Thanks, it works perfectly !

**Comment by ericrayanderson** [comment]
Seems like reasonable functionality to add.

**Comment by ericrayanderson** [comment]
select_material_tab(), selects a tab from the server

**Comment by bilbaoba** [comment]
We can close this one.
