### ISSUE TITLE
Shiny modules and update_material* functions

### ISSUE THREAD

**Issue by pommedeterresautee** [ericrayanderson/shinymaterial#82]
`update_material*` functions takes the name of the input object as a string instead of `input$name`.
When using [Shiny modules](https://shiny.rstudio.com/articles/modules.html), input names are transformed by the use of the `ns` function to avoid collisions between modules (basically it creates kind of name subspaces).
It took me times to realize that fact and that I should use `ns` function in the server part (but it should not be the case when you are using modules as they should).

To help user may be we want to have a check that the inpu name provided to `update_material*` function exists, and if it s not the case, having a message error with some advice about what to do inside.
What do you think?
https://shiny.rstudio.com/reference/shiny/0.14/NS.html

**Comment by bilbaoba** [comment]
If you look at the shiny update functions, they also take the name of the input object as a string. 
And I don't find any code looking if the input name exists and advice the user. 
I don't know if it is right to make global control into `update_material_*` only for the Shiny Module usage. 
Maybe you can propose a vignette exposing how to deal with shiny module.
