### ISSUE TITLE
Date picker from ShinyMaterial is hard to use compared to the materializecss version

### ISSUE THREAD

**Issue by pommedeterresautee** [ericrayanderson/shinymaterial#86]
In materializecss version it s quite easy to change the month or the year by clicking on it (top of the card).
https://materializecss.com/pickers.html
In Shiny Material, if you want to go to year 1800, you will have a hard time clicking hundreds of times on previous month arrow making it mostly unusable.
https://ericrayanderson.github.io/shinymaterial/

Is it a bug of due to a newer version of materialize CSS? Is it fixable?
Moreover it would be great to have some options like starting date, end date, etc.

**Comment by bilbaoba** [comment]
I seems you can do it into the library materialize v0.99.0; but only for the years. 
I check the doc for this version.

![image](https://user-images.githubusercontent.com/10165800/54434136-f7ab6b00-4746-11e9-9b34-2acdd625d26c.png)

By the way, if you want to consult the doc for this version :

```bash
git clone https://github.com/Dogfalo/materialize
cd materialize
git checkout v0.99.0
npm install

# Then run 
grunt monitor
```

When it finishes, open a new browser window and navigate to `localhost:8000`.

I will check this issue and try to propose a PR, maybe Eric forgot a class or an option.

**Comment by bilbaoba** [comment]
Find it ! 
Date Picker need specific initialization to create the dropdown control for month. 

```js
$('.datepicker').pickadate({
    selectMonths: true, // Creates a dropdown to control month
    selectYears: 15 // Creates a dropdown of 15 years to control year
});
```

**Comment by ericrayanderson** [comment]
new date picker in upcoming version
