### ISSUE TITLE
material_date_picker not working on new version of chrome

### ISSUE THREAD

**Issue by AlistairLR112** [ericrayanderson/shinymaterial#88]
Video of issue happening https://www.youtube.com/watch?v=Awrh-Bc4aVw

Currently running Chrome Version 73.0.3683.86 (Official Build) (64-bit)
shinymaterial version 0.5.5

**Comment by AlistairLR112** [comment]
Chrome has been updated and likely requires an update to the version of materialize being used.

**Comment by AlistairLR112** [comment]
video updated

**Comment by henrrynadalH** [comment]
I'm having the same issue, is there any solution to this problem?

**Comment by bilbaoba** [comment]
We need to migrate to the last version of javascript library materialize.

**Comment by Kvit** [comment]
+1

**Comment by Seyphaton** [comment]
same issue
- workaround: rick click the date picker

**Comment by Seyphaton** [comment]
> We need to migrate to the last version of javascript library materialize.

Is there a small chance that this happens in the near future?

**Comment by ericrayanderson** [comment]
Happening very shortly.
