### ISSUE TITLE
No 'Show entries' dropdown when working with DT library

### ISSUE THREAD

**Issue by lisovyk** [ericrayanderson/shinymaterial#9]
Sample:
```
library(shinymaterial)
library(DT)


ui <- material_page(
    DT::dataTableOutput("iris")
)

server <- function(input, output) {

    DTiris <- DT::renderDataTable({
        datatable(iris)
    })
    output$iris <- DTiris
}

shinyApp(ui = ui, server = server)
```
In the top left corner of the page you'll see "Show entries" sign, and there should be a dropdown nearby. Try changing `material_page` onto `fluidPage` to see what I'm talking about.

**Comment by lisovyk** [comment]
Tried on dev version, bugis still there

**Comment by ericrayanderson** [comment]
Tried the most recent dev version.

**Comment by lisovyk** [comment]
It seems a bit clumsy, but it works. Thanks!
