### ISSUE TITLE
material_dropdown do not work the first time in Chrome

### ISSUE THREAD

**Issue by jcverah** [ericrayanderson/shinymaterial#91]
The first time we press the control nothing happens, you have to press twice in order to get the list of choices displayed. This happens in Chrome, but not checked in other browsers

**Comment by AlistairLR112** [comment]
Related to https://github.com/ericrayanderson/shinymaterial/issues/88

**Comment by analytichealth** [comment]
Did anyone find a good work-around or fix for this? I'm using shiny::selectInput but it changes size and looks really bad @AlistairLR112 @jcverah @bilbaoba
