### ISSUE TITLE
showModal seems to not work with shinymaterial

### ISSUE THREAD

**Issue by oude-gao** [ericrayanderson/shinymaterial#95]
Shiny's modalDialog and showModal functionalities seem to be not working with shinymaterial:

` library(shiny)
  library(dplyr)
  library(shinymaterial)
  
  ui <- material_page(
    dataTableOutput('my_table'),
    actionButton('change','Change query')
  )
  
  server <- function(input,output,session)
  {
    # the modal dialog where the user can enter the query details.
    query_modal <- modalDialog(
      title = "Important message",
      selectInput('input_query','Select # cyl:',unique(mtcars$cyl)),
      easyClose = F,
      footer = tagList(
        actionButton("run", "Run query")
      )
    )
    
    # Show the model on start up ...
    showModal(query_modal)
    
    # ... or when user wants to change query
    observeEvent(input$change,
                 {
                   showModal(query_modal)
                 })
    
    # reactiveVal to store the dataset
    my_dataset <- reactiveVal()
    
    observeEvent(input$run, {
      removeModal()
      
      # Your query here
      my_data <- mtcars %>% filter(cyl %in% input$input_query)
      my_dataset(my_data)
      
    })
    
    # render the output
    output$my_table <- renderDataTable(my_dataset())
    
  }
  
  shinyApp(ui,server)`

Is there a workaround to enable pop-up dialog box or modal?

**Comment by analytichealth** [comment]
@oude-gao you will need to use the shinymaterial functions. Try this:

```
library(shiny)
library(shinymaterial)

ui <- material_page(
	# Define modal in the UI:
	material_modal(
		modal_id = 'important_message_modal',
		title = span('Important message',
			tags$i(class = 'material-icons', 'message')
		), 
		# choose icons from here: https://materializecss.com/icons.html
		display_button = F,
		button_text = '',
		close_button_label = 'Close',
		material_button(
			'run',
			label = 'Run query',
			icon = c('input'),
			depth = 2
		)
	),
	
	dataTableOutput('my_table'),
	actionButton('change', 'Change query')
	
)

server <- function(input, output, session) {
	
	# Open modal on start-up
	open_material_modal(session = session, modal_id = 'important_message_modal')
	
	
	# Open modal when clicking change button
	observeEvent(input$change, ignoreInit = T, {
		
		open_material_modal(session = session, modal_id = 'important_message_modal')
		
	})
	
	# Close modal
	observeEvent(input$run, ignoreInit = T, {
		# Perform actions here...
		
		close_material_modal(session = session, modal_id = 'important_message_modal')
		
	})
	
}

shinyApp(ui = ui, server = server)


```

**Comment by oude-gao** [comment]
Thanks so much! This is exactly what I wanted!
